labels: ["Use Cases"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an use case!
        
        This can help others imagine how they might use a package to address their research question and maybe provide some code for them to re-use. Sharing your use case can also go a long way to encouraging developers and maintainers, knowing there are others who appreciate and build on their work.
  - type: textarea
    id: resources
    attributes:
      label: rOpenSci package or resource used
      description: |
          For instance, one of our [packages](https://ropensci.org/packages/), our [package development guide](https://devguide.ropensci.org/), [Contributing Guide](https://contributing.ropensci.org/), a [Community Call](https://ropensci.org/commcalls/), or a [blog post](https://ropensci.org/blog/).
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What did you do?
      description: "Explain briefly what you did, to pique your readers' interest."
    validations:
      required: true
  - type: textarea
    id: url
    attributes:
      label: URL or code snippet for your use case
      description: |
          Link to a blog post, a gist, or an academic paper, or provide some code inline.
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: Language of the use case
      description: |
          Full name of the language, in English ("English", "Spanish", etc.)
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Image
      description: |
          For instance a figure from a paper or blog post if you have permission to share it.
    validations:
      required: true
  - type: dropdown
    id: sector
    attributes:
      label: Sector
      options:
        - Academic 
        - Industry
        - Government
        - Non-profit
        - Other
    validations:
      required: true
  - type: input
    id: field
    attributes:
      label: Field of application
      description: |
          Ecology, epidemiology, Antarctic and Southern Ocean research, biomedical research, energy, finance, history, social sciences, anything!
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: |
          Feedback or feature request.
    validations:
      required: true
  - type: input
    id: mastodon
    attributes:
      label: Mastodon profile URL
      description: |
          For potential mention when sharing your use case on social media.
    validations:
      required: false
  - type: input
    id: bluesky
    attributes:
      label: Bluesky profile URL
      description: |
          For potential mention when sharing your use case on social media.
    validations:
      required: false
