title: "[Use Case] "
labels: ["Use Cases"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an use case!
        
        This can help others imagine how they might use a package to address their research question and maybe provide some code for them to re-use. Sharing your use case can also go a long way to encouraging developers and maintainers, knowing there are others who appreciate and build on their work.
  - type: input
    id: resources
    attributes:
      label: rOpenSci package or resource used
      description: |
          For instance, one of our [packages](https://ropensci.org/packages/), 
          our [package development guide](https://devguide.ropensci.org/), 
          [Contributing Guide](https://contributing.ropensci.org/), 
          a [Community Call](https://ropensci.org/commcalls/), 
          or a [blog post](https://ropensci.org/blog/).
      value: |
        ...
    validations:
      required: true
  - type: input
    id: resources
    attributes:
      label: What did you do?
      description: "Explain briefly what you did, to pique your readers' interest."
      value: |
        ...
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_

