title: "[Use Case] "
labels: ["Use Cases"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template as a guide to share your use case for an rOpenSci package or resource. 
        
        This can help others imagine how they might use a package to address their research question and maybe provide some code for them to re-use. Sharing your use case can also go a long way to encouraging developers and maintainers, knowing there are others who appreciate and build on their work.
  - type: textarea
    id: resources
    attributes:
      label: rOpenSci package or resource used
      description: "_e.g. one of our [packages](https://ropensci.org/packages/), our [package development guide](https://devguide.ropensci.org/), [Contributing Guide](https://contributing.ropensci.org/), a [Community Call](https://ropensci.org/commcalls/), or a [blog post](https://ropensci.org/blog/)_"
      value: |
        
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_

